version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  redis:
    image: redis:7.2
    ports:
      - 6379:6379

